### ISSUE TITLE
How do I change the hovered and selected highlight colors of list items?

### ISSUE THREAD

**Issue by JackpotM1103** [salah-rashad/flutter_context_menu#2]
I have implemented the context list menu, and my current requirement is to change the highlight color of the list items when the mouse is hovering and long-pressed.

I didn't find the relevant implementation in MenuItem and ContextMenu

The following is my code implementation
```dart
List<ContextMenuEntry> getContextMenuEntries() {
    return List<ContextMenuEntry>.generate(
      contextMenuContent[type].length,
      (index) {
        Map<String, dynamic> item = contextMenuContent[type][index];
        if (item['children'] != null) {
          return MenuItem.submenu(
            label: item['label'],
            items: List<ContextMenuEntry>.from(item['children'].map(
                (ele) => MenuItem(label: ele['label'], value: ele['value']))),
          );
        }
        if (item['value'] == 'Divider') {
          return MenuDivider(color: Colors.grey.shade300);
        }
        return MenuItem(label: item['label'], value: item['value']);
      },
    );
  }
```

**Comment by salah-rashad** [comment]
The `MenuItem` provided by default uses the application's theme data. To customize it, you can modify your app's `colorScheme.onSurface`. 

Refer to the following code snippet for implementation details:
https://github.com/salah-rashad/flutter_context_menu/blob/a15468e288d5415422242a81f032d2cebdfc5ae8/lib/src/components/menu_item.dart#L59-L66

If you want a custom item for your app with the preferred properties, you can:
1. Copy the `MenuItem` class in your workspace folder.
2. Rename the class (optional)
3. customize and use it.

See the [example](https://github.com/salah-rashad/flutter_context_menu/tree/main/example) project for more information.

If you need further assistance please feel free to ask.

**Comment by JackpotM1103** [comment]
> The `MenuItem` provided by default uses the application's theme data. To customize it, you can modify your app's `colorScheme.onSurface`.
> 
> Refer to the following code snippet for implementation details:
> 
> https://github.com/salah-rashad/flutter_context_menu/blob/a15468e288d5415422242a81f032d2cebdfc5ae8/lib/src/components/menu_item.dart#L59-L66
> 
> If you want a custom item for your app with the preferred properties, you can:
> 
> 1. Copy the `MenuItem` class in your workspace folder.
> 2. Rename the class (optional)
> 3. customize and use it.
> 
> See the [example](https://github.com/salah-rashad/flutter_context_menu/tree/main/example) project for more information.
> 
> If you need further assistance please feel free to ask.

I have completed the function of customizing the highlight color, thanks for the tip
